psdm/topology/branch.py
psdm/topology/windings.py

feat: add neutral conductor information

---

.github/workflows/release.yml
.zenodo.json
CITATION.cff
README.md
pyproject.toml

feat: add link to zenodo

---

psdm/steadystate_case/controller.py

bug: control_type field of Controller not imported correctly for SteadyStateCase

---

.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.gitignore
psdm/topology/load.py

fix: add neutral phase to load

---

.zenodo.json
pyproject.toml

build: fix update of repo version in zenodo file

---

.github/workflows/checks.yml
.github/workflows/tests.yml
pdm.lock
psdm/topology/load_model.py

fix: correct numeric types in `LoadModel`

---

psdm/topology/load.py
tests/test_topology_load.py

feat: specify type of  `RatedPower`

---

psdm/topology/branch.py
psdm/topology/fuse.py

feat: add support for fuse types

---

pdm.lock
psdm/topology/load.py

feat: add separate connected phases for each load connection

---

.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/tests.yml
pdm.lock
pyproject.toml

feat: Support Python 3.11

---

README.md

fix: zenodo doi

---

psdm/topology/transformer.py

fix: vectorgroup 'YNyn5' is missing

---

psdm/meta.py

feat: topology case meta information

---

.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/tests.yml
psdm/topology/transformer.py

fix: zero sequence magnetisation information

---

psdm/topology/load.py

feat: add more Load/SystemType

---

psdm/topology/transformer.py

fix: allow only possible transformer vector groups

---

pdm.lock

build: upgrade deps

---

.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/tests.yml

build: update ci

---

psdm/base.py
psdm/steadystate_case/case.py
psdm/topology/load_model.py
psdm/topology/topology.py
psdm/topology/transformer.py
psdm/topology_case/case.py

fix: reenable unique constraints on object lists

---

psdm/meta.py

feat: add meta attr sign convention

---

pdm.lock
psdm/meta.py

fix: version does not get exported in metadata

---

README.md
psdm/topology/active_power.py
psdm/topology/load.py
psdm/topology/load_model.py
psdm/topology/reactive_power.py

fix: add reference voltage to load model

---

pdm.lock
psdm/base.py
psdm/topology/load.py
pyproject.toml

fix: handle quantities without phases

---

psdm/topology/external_grid.py

fix: add phase connections to external grid

---

psdm/topology/load.py

feat: remove `phase_connection_type`

---

psdm/quantities.py

feat:  add grid asset connected with earth as new load type

---

psdm/base.py
psdm/quantities/multi_phase.py
psdm/quantities/single_phase.py
psdm/topology/load.py
tests/test_multi_phase_quantities.py
tests/test_multi_power_factors.py
tests/test_single_phase_quantities.py

fix: powerfactor nan if ratedpower is zero

---

psdm/quantities/single_phase.py
psdm/topology/transformer.py

docs: precise abbreviations of power factor direction

---

psdm/quantities/single_phase.py

fix: add default system_type for Length

---

pdm.lock
psdm/meta.py
psdm/quantities/single_phase.py
psdm/topology/branch.py
psdm/topology/external_grid.py
psdm/topology/load.py
pyproject.toml

fix: freeze pydantic version to 2.5.3

---

.github/workflows/release.yml

build: fix release CI

---

psdm/steadystate_case/controller.py
tests/test_controller.py
tests/test_p_controller.py

fix: add p_set for ControlPF

---

psdm/steadystate_case/controller.py

docs: extend docs for controller

---

psdm/meta.py

feat: extend Meta with attribute `creator`

---

psdm/steadystate_case/controller.py

docs: add better description of Q(U)-Controller

---

psdm/topology_case/case.py

feat: validate topology case

---

psdm/base.py

fix: length of UniqueNonEmptyTuple

---

CONTRIBUTING.md
README.md

docs: update Readme  and CONTRIBUTING

---

src/psdm/topology/branch.py
tests/test_active_power.py
tests/test_controller.py
tests/test_multi_phase_quantities.py
tests/test_multi_power_factors.py
tests/test_p_controller.py
tests/test_q_controller.py
tests/test_reactive_power.py
tests/test_single_phase_quantities.py

fix: extend BranchType for series assets (RLC)

---

.github/workflows/create-release.yml

fix(ci): release workflow

---

pyproject.toml
uv.lock

build(deps): uv to 0.5.28, ruff to 0.9.4, pydantic to 2.10.6

---

.github/workflows/create-release.yml

build(ci): Update year in copyright notice in all files

---

.github/workflows/create-release.yml

fix: broken release pipeline
